export const introToCashflow = `# Introduction to Cashflow

## What is Cashflow?

Cashflow is a powerful real estate investment analysis tool designed to help investors, agents, and property enthusiasts make informed decisions about their real estate investments.

## Key Features

### Calculator Types for Various Investment Strategies

- **Rental Property Calculator**: Analyze potential long term residential rental properties
- **Fix & Flip Calculator**: Estimate profits for fixer upper projects
- **BRRRR Calculator**: Evaluate the Buy, Rehab, Rent, Refinance, Repeat strategy
- **Wholesale Calculator**: Calculate potential profits from wholesale deals
- **Price Target Calculator**: Determine ideal purchase prices based on your investment goals
- **Commercial Multi-Family**: Analyze commercial multi-family properties

## Getting Started

1. Open the Calculator of your choice on the Home Screen
2. Add your investment inputs and property details
3. Add your operating expenses
> You can either save the expenses input on the calculator screen or add them from your User Profile
4. View your investment results and analyze your future deal!
> All calculations are saved for you to review on the History Screen, with your most recent calculations displayed on the Home Screen

## Pro Tips

> All investment inputs and outputs have an Info Button that will detail the variable under question

> You may edit user account information from the User Profile Screen

> To provide feedback to Cashflow, please fill out the for on the Feedback Screen (accessable from the Home Screen)

### Happy Investing!`;

export default introToCashflow; 