//Inputs:
//Initial Loan: purchasePrice, downPayment, interestRate, loanTerm, closingCost
//Pre-refinance ONLY expenses: rehabCost, rehabTime, refinanceCost, operatingExpense (fixed costs)
//Both Expenses: propertyTax, operatingExpense (variable costs)
//Post-refinance ONLY expenses: BRRcapexEst, VacancyRate, BRRmonthRent
//Post-refinance Loan: NewInterest, NewLoanTerm, refinanceCost, afterRev

//Outputs: BRRCashflow, cashDown, CashOnCash, EquityReturnPerc, MaxEquity, BRRAnnualCashflow
//Outputs Expenses: BRRMortgageCost, BRRPropTax, monthlyOpEx, BRRCapEx